title: Abigail Adam's Homepage
# page-top-title: Portfolio
top-section-bg-text: Abigail Adam
home-subtitle: Engineering Physics Student
copyright-text: '&copy; Abigail Adam 2025. All Rights Reserved.'
